#!/bin/bash

INDEX_BEGIN=1
INDEX_END=8

function err() {
    echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
    exit 1
}

function check_iface() {
    local iface=$1
    iface_num=$(grep ${iface} /proc/interrupts | wc -l)
    if [[ $iface_num == 0 ]];then
        err "don't exist interface $iface, check and retry"
    fi
}

function is_multi_queue() {
    local iface=$1
    check_iface $iface
    iface_irq=$(grep "${iface}-" /proc/interrupts | wc -l)
    if [[ $iface_irq == 0 ]]; then
       return 1
    else
       return 0
    fi
}

function get_irq_num() {
    local iface=$1
    check_iface $iface
    iface_irq=$(grep "${iface}-" /proc/interrupts | wc -l)
    if [[ $iface_irq == 0 ]]; then
        iface_irq=$(grep ${iface} /proc/interrupts | wc -l)
    fi
    return $iface_irq
}

function set_hardwareirq() {
    if [[ $# < 3 ]];then
        usage
    fi
    local iface=$1
    check_iface $iface

    local index_begin=$2
    local index_end=$3
    local index_step=1
    if [[ $# = 4 ]];then
        index_step=$4
    fi

    local cpu_index_begin=${index_begin:-0};
    local cpu_index_end=${index_end:-3};
    local cpu_index_step=${index_step:-1};
    local index=${cpu_index_begin}

    if is_multi_queue $iface; then
        for irq in $(grep "${iface}-\|${iface}" /proc/interrupts | cut  -d:  -f1 | sed "s/ //g");do
            #echo ${cpu_index}
            cpu_index=$((1<<${index}))
            printf "%x" ${cpu_index} > /proc/irq/${irq}/smp_affinity;
            index=$((${index}+${cpu_index_step}))
            if [[ ${index} -ge ${cpu_index_end}+1 ]]; then
                index=${cpu_index_begin}
            fi
        done
    else
        local irq=$(grep "${iface}" /proc/interrupts | cut  -d:  -f1 | sed "s/ //g")
        local cpu_index=$((1<<${cpu_index_begin}))
        printf "%x" ${cpu_index} > /proc/irq/${irq}/smp_affinity;
    fi
}


function dump_hardwaredirq() {
    local iface=$1
    check_iface $iface

    echo "${iface} hardware irq config:"
    local rx=0
    for i in $(grep "${iface}-\|${iface}" /proc/interrupts | cut  -d:  -f1 | sed "s/ //g");do
        echo "rx-${rx} $(cat /proc/irq/$i/smp_affinity)"
        rx=$(($rx+1))
    done
}


function dump_flow_cnt() {
    local iface=$1
    check_iface $iface

    local sock_entries=262144

    iface_irq=$(grep "${iface}-" /proc/interrupts | wc -l)
    if [[ $iface_irq == 0 ]]; then
        iface_irq=$(grep ${iface} /proc/interrupts | wc -l)
    fi

    echo "total-flows: $(cat /proc/sys/net/core/rps_sock_flow_entries)"

    if is_multi_queue $iface;then
        for rx_num in $(seq 0 $(($iface_irq-1))); do
            echo "rx-${rx_num}-flow $(cat /sys/class/net/$iface/queues/rx-${rx_num}/rps_flow_cnt)"
        done
    else
        cat /sys/class/net/$iface/queues/rx-0/rps_flow_cnt
    fi
}

function set_flow_cnt() {
    local iface=$1
    check_iface $iface

    local sock_entries=262144
    echo $sock_entries > /proc/sys/net/core/rps_sock_flow_entries

    iface_irq=$(grep "${iface}-" /proc/interrupts | wc -l)
    if [[ $iface_irq == 0 ]]; then
        iface_irq=$(grep ${iface} /proc/interrupts | wc -l)
    fi
    rps_flow_cnt=$(($sock_entries/$iface_irq))
    if is_multi_queue $iface;then
        for rx_num in $(seq 0 $(($iface_irq-1))); do
            #echo $rx_num
            echo $rps_flow_cnt > /sys/class/net/$iface/queues/rx-${rx_num}/rps_flow_cnt
        done
    else
        echo $rps_flow_cnt > /sys/class/net/$iface/queues/rx-0/rps_flow_cnt
    fi
}

function set_softirq() {
    if [[ $# < 3 ]];then
        usage
    fi
    local iface=$1
    local index_begin=$2
    local index_end=$3
    local index_step=1
    if [[ $# = 4 ]];then
        index_step=$4
    fi
    check_iface $iface

    set_flow_cnt $iface

    local cpu_index_begin=${index_begin:-0};
    local cpu_index_end=${index_end:-3};
    local cpu_index_step=${index_step:-1};
    local index=${cpu_index_begin}
    for rx_queue in /sys/class/net/${iface}/queues/rx-*; do
        #echo ${cpu_index}
        cpu_index=$((1<<${index}))
        printf "%x" $cpu_index > ${rx_queue}/rps_cpus
        index=$((${index}+${cpu_index_step}))
        if [[ ${index} -ge ${cpu_index_end}+1 ]]; then
            index=${cpu_index_begin}
        fi
    done
}

function dump_softirq() {
    local iface=$1
    check_iface $iface

    echo "$iface softirq config:"
    for rx_queue in /sys/class/net/$iface/queues/rx-*; do
        echo "${rx_queue##*/} $(cat ${rx_queue}/rps_cpus)"
    done
    dump_flow_cnt $iface
}

usage() {
    echo "Usage: "
    echo "	$0 start iface cpu_index_begin cpu_index_end"
    echo "	$0 info iface "
    exit 1
}

function main() {
    local exec_mode=$1
    local iface=$2
    

    if [[ $exec_mode = "start" ]]; then
        if [[ $# != 4 ]];then
            usage
        fi
        local index_begin=$3
        local index_end=$4
    	set_hardwareirq ${iface} ${index_begin} ${index_end}
    	dump_hardwaredirq ${iface}
    	set_softirq ${iface} ${index_begin} ${index_end}
    	dump_softirq ${iface}
    elif [[ $exec_mode = "info" ]]; then
        if [[ $# != 2 ]];then
            usage
        fi
    	dump_hardwaredirq ${iface}
    	dump_softirq ${iface}
    else
        usage
    fi
}

main "$@"
