#!/bin/bash

exec 3<file
exec 4<file2

while true
do
    read -u 3 -r 7line
    read -u 4 -r 8line
    7option=`awk '{ print $2 }' $7line`
    8option=`awk '{ print $2 }' $8line`
    while [ "$7option" -eq "$8option" ]
    do
        echo $7line >> common.md
    done

    while [ "$7line" -gt x"$8line" ]
    do
        echo $8line >> 8only.md
        read -u 4 -r 8line
    done

    while x"$7line" < x"$8line"
    do
        echo $7line >> 7only.md
        read -u 4 -r 7line
    done
done

function while_read() {
    while read LINE
    do
        echo $LINE
    done < $FILENAME
}

function while_read_line(){
    cat $FILENAME | while read LINE
    do
        echo $LINE
    done
}

function while_read_line_by_fd(){
    exec 3<&0
    exec 0< $FILENAME
    while read LINE
    do
        echo $LINE
    done
    exec 0<&3
}

function for_read(){
    for i in  `cat $FILENAME`
    do
        echo $i
    done
}
