#! /bin/bash

if [[ $UID != 0 ]]
then
    INFO " This script neeeds to be run with sudo, like this:"
    echo -e "\n  sudo $0 $*\n"
    exit 1
fi

if [[ -f /etc/redhat-release ]]; then
    rpm -aq | grep yum | xargs rpm -e --nodeps
    wget http://mirrors.163.com/centos/6/os/x86_64/Packages/python-iniparse-0.3.1-2.1.el6.noarch.rpm | \
    curl http://mirrors.163.com/centos/6/os/x86_64/Packages/python-iniparse-0.3.1-2.1.el6.noarch.rpm \
        -o python-iniparse-0.3.1-2.1.el6.noarch.rpm

    wget
    http://mirrors.163.com/centos/6/os/x86_64/Packages/yum-metadata-parser-1.1.2-16.el6.x86_64.rpm |\
    curl http://mirrors.163.com/centos/6/os/x86_64/Packages/yum-metadata-parser-1.1.2-16.el6.x86_64.rpm \
        -o yum-metadata-parser-1.1.2-16.el6.x86_64.rpm

    wget
    http://mirrors.163.com/centos/6/os/x86_64/Packages/yum-3.2.29-69.el6.centos.noarch.rpm |\
    curl http://mirrors.163.com/centos/6/os/x86_64/Packages/yum-3.2.29-69.el6.centos.noarch.rpm \
        -o yum-3.2.29-69.el6.centos.noarch.rpm

    wget http://mirrors.163.com/centos/6/os/x86_64/Packages/yum-plugin-fastestmirror-1.1.30-30.el6.noarch.rpm |\
    curl http://mirrors.163.com/centos/6/os/x86_64/Packages/yum-plugin-fastestmirror-1.1.30-30.el6.noarch.rpm \
        -o yum-plugin-fastestmirror-1.1.30-30.el6.noarch.rpm

    rpm -ivh python-iniparse-0.3.1-2.1.el6.noarch.rpm
    rpm -ivh yum-metadata-parser-1.1.2-16.el6.x86_64.rpm
    rpm -ivh yum-3.2.29-69.el6.centos.noarch.rpm yum-plugin-fastestmirror-1.1.30-30.el6.noarch.rpm
    cd /etc/yum.repos.d/
    for f in `ls`; do mv $f $f.bak ; done
    wget http://mirrors.163.com/.help/CentOS6-Base-163.repo | \
    curl http://mirrors.163.com/.help/CentOS6-Base-163.repo -o CentOS6-Base-163.repo
    rpm --import http://mirrors.163.com/centos/RPM-GPG-KEY-CentOS-6
    sed -i "s/\$releasever/6/" CentOS6-Base-163.repo
    yum clean all
    yum makecache

    yum -y install epel-release
    sed -i "s/#baseurl/baseurl/" /etc/yum.repos.d/epel.repo
    sed -i "s/mirrorlist/#mirrorlist/" /etc/yum.repos.d/epel.repo
    yum makecache
else
    echo "only support REDHAT"
    exit 1
fi
