#! /bin/bash

count=0
while true; do
    sleep 5
    netstat -ant | grep ES | awk '{ print  $4 " " $5  }' >> /tmp/ip_list
    count=$(( $count + 1 ))
    if (( $count == 100 )); then
        awk '!_[$2]++{print}' /tmp/ip_list >> /home/wenxueliu/ip_list
        count=0
    fi
done


