#! /bin/bash

#Author : Wenxue Liu
#Update : 2015-10-09

#TODO getopt  as follow
INSTALL_FORCE=true
JAVA8_VERSION=8u91
JAVA8_URL=${JAVA8_VERSION}-b14
JAVA8_MD5="3f3d7d0cd70bfe0feab382ed4b0e45c0"
JAVA8_PRIORITY=1800911

JAVA7_VERSION=7u79
JAVA7_URL=${JAVA7_VERSION}-b15

JAVA_VERSION=$JAVA8_VERSION # JAVA_VERSION=8u60
JAVA_MD5=$JAVA8_MD5
JAVA_PREFIX="/opt"  # end without "/"
PRIORITY=$JAVA8_PRIORITY
PACKEGE_PATH="."

#################################################################
#		   LOGGER
#################################################################
LOG_LEVEL_ON=0
LOG_LEVEL_TRACE=1
LOG_LEVEL_DEBUG=2
LOG_LEVEL_INFO=3
LOG_LEVEL_WARN=4
LOG_LEVEL_ERROR=5
LOG_LEVEL_FATAL=6
LOG_LEVEL_OFF=7

LOG_LEVEL=$LOG_LEVEL_INFO

ECHO_LOG() {
    [ "$1" -ge $LOG_LEVEL ] && echo -e "\033[31m $2:\033[0m $3" >&2
}

TRACE() {
    ECHO_LOG $LOG_LEVEL_TRACE "TRACE" "$1"
}

DEBUG() {
    ECHO_LOG $LOG_LEVEL_DEBUG "DEBUG" "$1"
}

INFO() {
    ECHO_LOG $LOG_LEVEL_INFO "INFO" "$1"
}

WARN() {
    ECHO_LOG $LOG_LEVEL_WARN  "WARN" "$1"
}

ERROR() {
    ECHO_LOG $LOG_LEVEL_ERROR "ERROR" "$1"
}

FATAL() {
    ECHO_LOG $LOG_LEVEL_FATAL "FATAL" "$1" && exit 1
}

#########################################################################

FORCE_MODE() {
    [[ $INSTALL_FORCE == false ]] && echo -e "INSTALL_FORCE = $INSTALL_FORCE, \n exit" && exit 0
}

PLATFORM=`uname`
ARCH=`uname -p`
OS="UnKnow"

if [[ $UID != 0 ]]
then
    INFO " This script neeeds to be run with sudo, like this:"
    echo -e "\n  sudo $0 $*\n"
    exit 1
fi

if [[ -f /etc/debian_version ]]
then
    OS="Debian"
elif [[ -f /etc/redhat-release ]]
then
    OS="RedHat"
else
    OS="UnKnow"
fi

INFO "operate system : `cat /etc/redhat-release`" 

if [[ $OS == "RedHat" ]]; then
    sudo yum install wget
elif [[ $OS == "Debian" ]]; then
    sudo apt-get install wget
fi
###################################################################
#                   Java (1.7.0_79 OR 1.8.0_60)
# Only Linux RedHat support
# 参考
# http://tecadmin.net/steps-to-install-java-on-centos-5-6-or-rhel-5-6/
# http://askubuntu.com/questions/56104/how-can-i-install-sun-oracles-proprietary-java-jdk-6-7-8-or-jre
###################################################################

if [[ $PLATFORM == "Linux" ]]
then
    INFO "platform :$PLATFORM"
    if [[ -z ${JAVA_HOME} ]]; then
        # Find the actual location of the Java launcher: Compute the Java home from the location of the Java launcher:
        java_launcher=`which java 2> /dev/null` && java_launcher=`readlink -f "${java_launcher}"` \
		&& JAVA_HOME="${java_launcher%/bin/java}"
        if [[ -n ${JAVA_HOME} ]]; then
            WARN "java is installed in $JAVA_HOME" && FORCE_MODE
        fi
    else
        WARN "java is installed in $JAVA_HOME" && FORCE_MODE
    fi
else
    ERROR "Only Linux Debian and RedHat 5/6/7 support"
    exit 1
fi

# Download Java Version

JAVA_PACKAGE=""

if [[ $ARCH == "x86_64" ]]
then
    INFO "arch :  $ARCH"
    JAVA_PACKAGE=jdk-${JAVA_VERSION}-linux-x64.tar.gz
    if [[ $JAVA_VERSION == $JAVA7_VERSION ]]
    then
        INFO "expect install java version $JAVA_VERSION"
        if [[ -f $PACKEGE_PATH/$JAVA_PACKAGE ]]; then
            INFO "java tar package has been download, skip"
        else
            INFO "begin download java ...."
            wget --no-cookies --no-check-certificate --header "Cookie: \
            gpw_e24=http%3A%2F%2Fwww.oracle.com%2F;                    \
            oraclelicense=accept-securebackup-cookie"                  \
            "http://download.oracle.com/otn-pub/java/jdk/${JAVA7_URL}/$JAVA_PACKAGE"
            INFO "download java done"
        fi
        PACKAGE_MD5=`md5sum $JAVA_PACKAGE | awk '{ print $1 }'`
        if [[ $PACKAGE_MD5 == $JAVA_MD5 ]]; then
            DEBUG "md5 checksum successfully"
        else
            ERROR "md5 expect $JAVA_MD5 but the package is $PACKAGE_MD5" && exit 1
        fi
    elif [[ $JAVA_VERSION == $JAVA8_VERSION ]]
    then
        INFO "expect install java version $JAVA_VERSION"
        if [[ -f $PACKEGE_PATH/$JAVA_PACKAGE ]]; then
            INFO "java tar package has been download, skip"
        else
            INFO "begin download java ...."
            wget --no-cookies --no-check-certificate --header "Cookie: \
            gpw_e24=http%3A%2F%2Fwww.oracle.com%2F;                    \
            oraclelicense=accept-securebackup-cookie"                  \
            "http://download.oracle.com/otn-pub/java/jdk/${JAVA8_URL}/$JAVA_PACKAGE"
            INFO "download java done"
        fi
        PACKAGE_MD5=`md5sum $JAVA_PACKAGE | awk '{ print $1 }'`
        if [[ $PACKAGE_MD5 == $JAVA_MD5 ]]; then
            DEBUG "md5 checksum successfully"
        else
            ERROR "md5 expect $JAVA_MD5 but the package is $PACKAGE_MD5" && exit 1
        fi
    else
        FATAL "no support java version"
    fi
else
    INFO "arch :  $ARCH"
    JAVA_PACKAGE=jdk-${JAVA_VERSION}-linux-i586.tar.gz
    if [[ $JAVA_VERSION == $JAVA7_VERSION ]]
    then
        INFO "expect install java version $JAVA_VERSION"
        if [[ -f $PACKEGE_PATH/$JAVA_PACKAGE ]]; then
            INFO "java tar package has been download, skip"
        else
            INFO "begin download java ...."
            wget --no-cookies --no-check-certificate --header "Cookie: \
            gpw_e24=http%3A%2F%2Fwww.oracle.com%2F;                    \
            oraclelicense=accept-securebackup-cookie"                  \
            "http://download.oracle.com/otn-pub/java/jdk/${JAVA7_URL}/$JAVA_PACKAGE" \
            || (INFO "download java package error, retry it." && exit 1)

        fi
        PACKAGE_MD5=``md5sum $JAVA_PACKAGE | awk '{ print $1 }'``
        if [[ $PACKAGE_MD5 == $JAVA_MD5 ]]; then
            DEBUG "md5 checksum successfully"
        else
            ERROR "md5 expect $JAVA_MD5 but the package is $PACKAGE_MD5" && exit 1
        fi
    elif [[ $JAVA_VERSION == $JAVA8_VERSION ]]
    then
        #only java 8u91
        JAVA_MD5=21322b66a0839ffb08d6c45d73ef48b8
        INFO "expect install java version $JAVA_VERSION"
        if [[ -f $PACKEGE_PATH/$JAVA_PACKAGE ]]; then
            INFO "java tar package has been download, skip"
        else
            INFO "begin download java ...."
            wget --no-cookies --no-check-certificate --header "Cookie: \
            gpw_e24=http%3A%2F%2Fwww.oracle.com%2F;                    \
            oraclelicense=accept-securebackup-cookie"                  \
            "http://download.oracle.com/otn-pub/java/jdk/${JAVA8_URL}/$JAVA_PACKAGE" \
            || (INFO "download java package error, retry it." && exit 1)
        fi
        PACKAGE_MD5=``md5sum $JAVA_PACKAGE | awk '{ print $1 }'``
        if [[ $PACKAGE_MD5 == $JAVA_MD5 ]]; then
            DEBUG "md5 checksum successfully"
        else
            ERROR "md5 expect $JAVA_MD5 but the package is $PACKAGE_MD5" && exit 1
        fi
    else
        FATAL "no support java version"
    fi
fi

INFO "download java package at $JAVA_PACKAGE"

JAVA_DIR=""
#TODO jdk is exist
if ! ls $JAVA_PREFIX | grep jdk >> /dev/null
then
    if [[ $JAVA_VERSION == $JAVA7_VERSION ]]
    then
        tar xzf $JAVA_PACKAGE -C $JAVA_PREFIX
        JAVA_DIR="jdk1.7.0_79"
    elif [[ $JAVA_VERSION == $JAVA8_VERSION ]]
    then
        tar xzf $JAVA_PACKAGE -C $JAVA_PREFIX
        JAVA_DIR="jdk1.8.0_91"
    else
        echo "not support java version"
        exit 1
    fi
else
    JAVA_DIR=`ls $JAVA_PREFIX | grep jdk`
    WARN "jdk has been extaracted at $JAVA_PREFIX" && FORCE_MODE
fi

#Install Java with Alternatives

JAVA_PATH="$JAVA_PREFIX/$JAVA_DIR"
mkdir -p $JAVA_PREFIX; cd $JAVA_PATH


#if java, javac, jar installed, exit 0; man alternatives
if [[ $OS == "RedHat" ]]
then
    alternatives --display java 2> /dev/null && WARN "java has been configed " && FORCE_MODE \
|| alternatives --install /usr/bin/java java $JAVA_PATH/bin/java $PRIORITY
    alternatives --set java $JAVA_PATH/bin/java

    alternatives --display jar &&  WARN "jar has been configed "  && FORCE_MODE \
|| alternatives --install /usr/bin/jar jar $JAVA_PATH/bin/jar $PRIORITY
    alternatives --set  jar $JAVA_PATH/bin/jar

    alternatives --display javac && WARN "javac has been configed " && FORCE_MODE \
|| alternatives --install /usr/bin/javac javac $JAVA_PATH/bin/javac $PRIORITY 
    alternatives --set  javac $JAVA_PATH/bin/javac

elif [[ $OS == "Debian" ]]
then
    #TODO
    echo "Debian"
    #sudo mv ./jdk1.7* /usr/lib/jvm/jdk1.7.0
    update-alternatives --display java 2> /dev/null && WARN "java has been configed " && FORCE_MODE \
|| update-alternatives --install /usr/bin/java java $JAVA_PATH/bin/java $PRIORITY
    update-alternatives --set java $JAVA_PATH/bin/java

    update-alternatives --display jar &&  WARN "jar has been configed "  && FORCE_MODE \
|| update-alternatives --install /usr/bin/jar jar $JAVA_PATH/bin/jar $PRIORITY
    update-alternatives --set  jar $JAVA_PATH/bin/jar

    update-alternatives --display javac && WARN "javac has been configed " && FORCE_MODE \
|| update-alternatives --install /usr/bin/javac javac $JAVA_PATH/bin/javac $PRIORITY 
    update-alternatives --set  javac $JAVA_PATH/bin/javac

    #sudo chmod a+x /usr/bin/java
    #sudo chmod a+x /usr/bin/javac
    #sudo chmod a+x /usr/bin/javaws
    #sudo chown -R root:root $JAVA_PATH
fi

#Check Installed Java Version
java -version

#RC_FILE="~/.bashrc"
RC_FILE="/etc/environment"
RC_DIR=`dirname $RC_FILE`
mkdir -p $RC_DIR
#touch $RC_FILE
#Configuring Environment Variables
#in /etc/environment
if  grep "JAVA_HOME" $RC_FILE; then
   WARN "JAVA_HOME has be configed"
   INFO "run 'echo \$JAVA_HOME'"
   INFO "    if echo \$JAVA_HOME is expected, skip it"
   INFO "    else delete JAVA_HOME from $RC_FILE, run this shell again"
   exit 1
elif grep "JRE_HOME" $RC_FILE ; then
   WARN "JRE_HOME has be configed"
   INFO "run echo \$JRE_HOME"
   INFO "    if echo \$JRE_HOME is expected, skip it"
   INFO "    else delete JRE_HOME from $RC_FILE, run this shell again"
   exit 1
else

cat >> $RC_FILE <<EOF
export JAVA_HOME=$JAVA_PATH
export JRE_HOME=$JAVA_PATH/jre
export PATH=$PATH:$JAVA_PATH/bin:$JAVA_PATH/jre/bin
EOF

fi

source $RC_FILE

#Check Java is installed and Setting correctly
[[ -z ${JAVA_HOME} ]] && WARN "Need to set JAVA_HOME environment variable" && FORCE_MODE
[[ ! -x ${JAVA_HOME}/bin/java ]] && WARN "Cannot find an executable JVM at path ${JAVA_HOME}/bin/java check your JAVA_HOME" && FORCE_MODE

INFO "======================================================================="
INFO "if '\$JAVA_HOME=$JAVA_HOME' is null, relogin to make sure the java home is set"
INFO "======================================================================="

###########################################################################
# # Reference https://launchpad.net/~webupd8team/+archive/ubuntu/java
# Ubuntu
# sudo apt-get install python-software-properties
# add-apt-repository ppa:webupd8team/java
# apt-get update
# #Java 8
# apt-get install oracle-java8-installer
# apt-get install oracle-java8-set-default
# #Java 7
# apt-get install oracle-java8-installer
# apt-get install oracle-java8-set-default
# java -version
# FireFox 
# mkdir ~/.mozilla/plugins
# ln -s /usr/lib/jvm/jdk1.7.0/jre/lib/amd64/libnpjp2.so ~/.mozilla/plugins/
# sudo /etc/init.d/apparmor restart
############################################################################
