java -classpath classes/ -jar lib/netty-3.2.6.Final.jar org.jboss.netty.example.discard.DiscardServer
javac src/DiscardServer.java src/DiscardServerHandler.java -d lib/ -classpath lib/netty-3.2.6.Final.jar
